version: '3.3'

services:
  db:
    image: mongo:${MONGO_VERSION}
    deploy:
      placement:
        constraints:
          - node.labels.reliability == high
    volumes:
      - mongo_data:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  post:
    image: ${USERNAME}/post:${POST_VERSION}
    deploy:
      mode: replicated
      replicas: 4
      placement:
        constraints:
          - node.role == worker
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: rollback
      resources:
        limits:
          cpus: '0.3'
          memory: 300M
      restart_policy:
        condition: on-failure
        max_attempts: 13
        delay: 1s
    networks:
      - back_net
      - front_net
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: service.post
  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    deploy:
      mode: replicated
      replicas: 4
      placement:
        constraints:
          - node.role == worker
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: rollback
      resources:
        limits:
          cpus: '0.3'
          memory: 300M
      restart_policy:
        condition: on-failure
        max_attempts: 13
        delay: 1s
    networks:
      - back_net
      - front_net
  ui:
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${UI_PORT}:9292/tcp
    deploy:
      mode: replicated
      replicas: 4
      placement:
        constraints:
          - node.role == worker
      update_config:
        delay: 5s
        parallelism: 1
        failure_action: rollback
      resources:
        limits:
          cpus: '0.25'
          memory: 150M
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 3s
    networks:
      - front_net
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: service.ui
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - front_net

volumes:
  mongo_data:
  grafana_data:

networks:
  back_net:
  front_net:
