version: '3.3'

services:
  db:
    image: mongo:3.2
    volumes:
      - db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      - back_net
      - front_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - back_net
      - front_net
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${PORT}:9292/tcp
    networks:
      - front_net

volumes:
  db:

networks:
  back_net:
  front_net:
