version: '3.3'

services:
  db:
    image: mongo:3.2
    volumes:
      - db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  post:
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      - back_net
      - front_net
  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - back_net
      - front_net
  ui:
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${PORT}:9292/tcp
    networks:
      - front_net
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    networks:
      - back_net
      - front_net
  node-exporter:
    image: prom/node-exporter:v0.15.0
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net
      - front_net

volumes:
  db:

networks:
  back_net:
  front_net:
